# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreativeWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('creator', models.CharField(max_length=100)),
                ('abscrete_type_creativework', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('creativework_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='example_app.CreativeWork')),
                ('text', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('example_app.creativework',),
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('creativework_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='example_app.CreativeWork')),
                ('duration_in_minutes', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('example_app.creativework',),
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='example_app.Article')),
                ('newspaper_name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('example_app.article',),
        ),
        migrations.CreateModel(
            name='SocialMediaPosting',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='example_app.Article')),
                ('url', models.URLField()),
            ],
            options={
                'abstract': False,
            },
            bases=('example_app.article',),
        ),
    ]
